import typing
import collections.abc
import typing_extensions

def add_scrollback(text, text_type): ...
def autocomplete(_context): ...
def banner(context): ...
def execute(context, _is_interactive): ...
def shell_run(text): ...
